# searching for s, many files:
s_array: [0.09,0.1,0.11]
exp_root: "/data/ephraim/datasets/known_noise/undiff_exps/exp_o_net4mog/"
network: "NetworkNoise4MoG"
epochs: 45
min_epochs: 30
slope_epochs: 8
dataset_size: 1*1
n_samples: 15
batch_size: 1
snr_array: ["5"]
test_start_sec: 4
test_end_sec: 9
test_start_sec_noise: 220
test_end_sec_noise: 225
val_len: 5
mog: 5


