# parameters:
s_array: [0.08,0.09,0.1,0.11, 0.12,0.15,0.01,0.05,0.2,0.25,0.28,0.3,0.33,0.35,0.07]
exp_root: "/data/ephraim/datasets/known_noise/undiff_exps/exp_m_long_ar_long/"
network: "NetworkNoise2"
epochs: 200
dataset_size: 2*8
n_samples: 640000
batch_size: 16
snr_array: ["5"]

