# searching for s, many files:
s_array: [0.07,0.09,0.1,0.11,0.15,0.2,0.23,0.25,0.28,0.3,0.33,0.35,0.4]
exp_root: "/data/ephraim/datasets/known_noise/undiff_exps/exp_n_chosen/"
network: "NetworkNoise4"
epochs: 1700
dataset_size: 1*1
n_samples: 1
batch_size: 1
snr_array: ["5"]

