# searching for s, many files:
s_array: [0.07,0.09,0.1,0.11,0.15,0.2,0.23,0.25,0.28,0.3,0.33,0.35,0.4]
exp_root: "/data/ephraim/datasets/known_noise/undiff_exps/exp_n_chosen_whole_8gt/"
network: "NetworkNoise8"
epochs: 
min_epochs:
slope_epochs:
dataset_size: 1*1
n_samples: 1
batch_size: 1
trained_model_path: "/data/ephraim/datasets/known_noise/undiff_exps/training_all/all_noises_net8_gt/model_step3265000.pth"
snr_array: ["5"]
test_start_sec: 6
test_end_sec: 10

