defaults:
  - task: unconditional
  - model: diffwave
  - diffusion: gaussian_diffusion
  - _self_

output_dir: results/guided
audio_dir: 1
use_ema: false
segment_size: null
sampling_rate: 16000
device: cuda
guidance: true
guid_s: 0.1
cur_noise_var: null
y_noisy: /data/ephraim/datasets/known_noise/undiff_exps/exp_p4_net3_6/18/noisy_wav/noise18_LJ050-0271_snr5_fileid_18.wav
outpath: /data/ephraim/datasets/known_noise/undiff_exps/exp_p4_net3_6/18/enhanced_60/snr5/s0.1
clean_wav: null
s_schedule: 60
noise_type: y_model
noise_model_path: /data/ephraim/datasets/known_noise/undiff_exps/exp_p4_net3_6/18/0_snr5_18_models.pickle
l_low: 0.2
network: null #"NetworkNoise8"
mog: 0
