defaults:
  - task: unconditional
  - model: diffwave
  - diffusion: gaussian_diffusion
  - _self_

output_dir: results/guided
audio_dir: 1
use_ema: false
segment_size: null
sampling_rate: 16000
device: cuda
guidance: true
guid_s: 0.000001
cur_noise_var: null
y_noisy: /data/ephraim/datasets/known_noise/undiff_exps/exp_n_chosen_whole_8/34/noisy_wav/noise34_book_07277_chp_0048_reader_11272_3_LohqmNzxccQ_snr5_fileid_34.wav
outpath: /data/ephraim/datasets/known_noise/undiff_exps/exp_n_chosen_whole_8/34/enhanced_60/snr5/s0.1
clean_wav: null
s_schedule: 60
noise_type: loss_model
noise_model_path: /data/ephraim/datasets/known_noise/undiff_exps/training_all/all_noises_net8b/model_step2721000.pth
l_low: 0.2
network: NetworkNoise8 #"NetworkNoise8"



