defaults:
  - task: unconditional
  - model: diffwave
  - diffusion: gaussian_diffusion
  - _self_

output_dir: results/guided
audio_dir: 1
use_ema: false
segment_size: null
sampling_rate: 16000
device: cuda
guidance: true
guid_s: 0.05
cur_noise_var: null
y_noisy: /data/ephraim/datasets/known_noise/undiff_exps/exp_m_net6mog5/p/noisy_wav/noise1_digits_snr5_power0.0005413281032815576_var0.00044461217476055026.wav
outpath: /data/ephraim/datasets/known_noise/undiff_exps/exp_m_net6mog5/p/enhanced_60/snr5/s0.05
clean_wav: null
s_schedule: 60
noise_type: loss_model_mog
noise_model_path: /data/ephraim/datasets/known_noise/undiff_exps/exp_m_net6mog5/p/0_snr5_1_models.pickle
l_low: 0.2
network: null #"NetworkNoise8"
mog: 5



