defaults:
  - task: bwe
  - model: diffwave
  - diffusion: gaussian_diffusion
  - _self_

output_dir: results
audio_dir: ???
use_ema: false
segment_size: null
sampling_rate: 16000
device: cuda
guidance: true
guid_s: 0.001
cur_noise_var: null
y_noisy: "/data/ephraim/datasets/known_noise/exp3b/noisy_wav/digits_snr5_power0.0012988714734092355_var0.0012939611915498972.wav"
outpath: /data/ephraim/datasets/known_noise/undiff/exp3b/enhanced/
clean_wav: null
s_schedule: null
noise_type: loss_model
noise_model_path: /data/ephraim/repos/Pytorch-VAE-tutorial/exp1.pickle
l_low: 0.2
